/*! 
* DevExtreme Web
* Version: 14.2.3
* Build date: Dec 3, 2014
*
* Copyright (c) 2012 - 2014 Developer Express Inc. ALL RIGHTS RESERVED
* EULA: https://www.devexpress.com/Support/EULAs/DevExtreme.xml
*/

Globalize.addCultureInfo("es", {messages: {
        Yes: "Si",
        No: "No",
        Cancel: "Cancelar",
        Clear: "Limpiar",
        Done: "Hecho",
        Loading: "Cargando...",
        Select: "Seleccionar...",
        Search: "Buscar...",
        Back: "Atrás",
        OK: "OK"
        //"dxCollectionWidget-noDataText": "Keine Daten verfügbar",
        //"validation-required": "Pflichtfeld",
        //"validation-required-formatted": "{0} ist ein Pflichtfeld",
        //"validation-numeric": "Der Wert muss eine Zahl sein",
        //"validation-numeric-formatted": "{0} muss eine Zahl sein",
        //"validation-range": "Der Wert ist nicht im gültigen Bereich",
        //"validation-range-formatted": "{0} ist nicht im gültigen Bereich",
        //"validation-stringLength": "Die Länge des Wertes ist nicht korrekt",
        //"validation-stringLength-formatted": "Die Länge von {0} ist nicht korrekt",
        //"validation-custom": "Der Wert ist ungültig",
        //"validation-custom-formatted": "{0} ist ungültig",
        //"validation-compare": "Der Wert ist unpassend",
        //"validation-compare-formatted": "{0} ist unpassend",
        //"validation-pattern": "Der Wert passt nicht zum Muster",
        //"validation-pattern-formatted": "{0} passt nicht zum Muster",
        //"validation-email": "Die Email-Adresse ist ungültig",
        //"validation-email-formatted": "{0} ist ungültig"
    }});
//Globalize.addCultureInfo("de", {messages: {
//        "dxLookup-searchPlaceholder": "Minimale Anzahl Zeichen: {0}",
//        "dxList-pullingDownText": "Zum Aktualisieren nach unten ziehen",
//        "dxList-pulledDownText": "Zum Aktualisieren loslassen",
//        "dxList-refreshingText": "Aktualisiere...",
//        "dxList-pageLoadingText": "Laden...",
//        "dxList-nextButtonText": "Mehr",
//        "dxList-selectAll": "Alles auswählen",
//        "dxListEditDecorator-delete": "Entfernen",
//        "dxListEditDecorator-more": "Mehr",
//        "dxScrollView-pullingDownText": "Zum Aktualisieren nach unten ziehen",
//        "dxScrollView-pulledDownText": "Zum Aktualisieren loslassen",
//        "dxScrollView-refreshingText": "Aktualisiere...",
//        "dxScrollView-reachBottomText": "Laden...",
//        "dxDateBox-simulatedDataPickerTitleTime": "Zeit auswählen",
//        "dxDateBox-simulatedDataPickerTitleDate": "Datum auswählen",
//        "dxDateBox-simulatedDataPickerTitleDateTime": "Datum und Zeit auswählen",
//        "dxFileUploader-selectFile": "Datei auswählen",
//        "dxFileUploader-dropFile": "oder hierher ziehen",
//        "dxFileUploader-bytes": "Bytes",
//        "dxFileUploader-kb": "kb",
//        "dxFileUploader-Mb": "Mb",
//        "dxFileUploader-Gb": "Gb"
//    }});
Globalize.addCultureInfo("es", {messages: {
        "dxDataGrid-columnChooserTitle": "Selección de columnas",
        "dxDataGrid-columnChooserEmptyText": "Arrastre aquí para ocultar Columnas",
        "dxDataGrid-groupContinuesMessage": "Página siguiente",
        "dxDataGrid-groupContinuedMessage": "Página anterior",
        "dxDataGrid-editingEditRow": "Editar",
        "dxDataGrid-editingSaveRowChanges": "Guardar",
        "dxDataGrid-editingCancelRowChanges": "Abortar",
        "dxDataGrid-editingDeleteRow": "Quitar",
        "dxDataGrid-editingUndeleteRow": "Restaurar",
        "dxDataGrid-editingConfirmDeleteMessage": "¿Seguro que quieres eliminar este registro?",
        "dxDataGrid-editingConfirmDeleteTitle": "Confirmar",
        "dxDataGrid-groupPanelEmptyText": "Arrastre una columna aquí para agrupar a continuación",
        "dxDataGrid-noDataText": "No hay datos",
        "dxDataGrid-searchPanelPlaceholder": "Buscar ...",
        "dxDataGrid-filterRowShowAllText": "(Todos)",
        "dxDataGrid-filterRowResetOperationText": "Retornar",
        "dxDataGrid-filterRowOperationEquals": "Es igual a",
        "dxDataGrid-filterRowOperationNotEquals": "No es igual a",
        "dxDataGrid-filterRowOperationLess": "Menor que",
        "dxDataGrid-filterRowOperationLessOrEquals": "Menor o igual",
        "dxDataGrid-filterRowOperationGreater": "Mayor que",
        "dxDataGrid-filterRowOperationGreaterOrEquals": "Mayor o igual que",
        "dxDataGrid-filterRowOperationStartsWith": "Empieza con",
        "dxDataGrid-filterRowOperationContains": "Contiene",
        "dxDataGrid-filterRowOperationNotContains": "No contiene",
        "dxDataGrid-filterRowOperationEndsWith": "Termina con",
        "dxDataGrid-applyFilterText": "Aplicar filtros",
        "dxDataGrid-trueText": "Verdadero",
        "dxDataGrid-falseText": "Falso",
        "dxDataGrid-sortingAscendingText": "Orden ascendente",
        "dxDataGrid-sortingDescendingText": "Orden descendente",
        "dxDataGrid-sortingClearText": "Quitar orden",
        "dxDataGrid-editingSaveAllChanges": "Guardar cambios",
        "dxDataGrid-editingCancelAllChanges": "Cancelar cambios",
        "dxDataGrid-editingAddRow": "Nueva línea",
        "dxDataGrid-summaryMin": "Min: {0}",
        "dxDataGrid-summaryMinOtherColumn": "Mínimo de {1} es {0}",
        "dxDataGrid-summaryMax": "Max: {0}",
        "dxDataGrid-summaryMaxOtherColumn": "Máximo de {1} es {0}",
        "dxDataGrid-summaryAvg": "Ø: {0}",
        "dxDataGrid-summaryAvgOtherColumn": "Promedio de {1} es {0}",
        "dxDataGrid-summarySum": "{0}",
        "dxDataGrid-summarySumOtherColumn": "Suma de {1} es {0}",
        "dxDataGrid-summaryCount": "Total Filas: {0}",
        "dxPager-infoText": "Página {0} de {1}"
    }});
